# Generated by Django 4.2.30 on 2026-09-16 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0002_detalleorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_trabajo', to=settings.AUTH_USER_MODEL),
        ),
    ]
